menu:
  Home: /
  Archives: /archives
  About Me: /AboutMe
  RSS: /atom.xml

# gitment
gitment: true
gitment_owner: 'XueshiQiao'
gitment_repo: 'GitmentOfMyBlog'
gitment_client_id: '48ebf2dbd107227f4c9b'
gitment_client_secret: 'c81de17c91d1289347e35167fce08a88ed4766c5'

# google analytics
googleTrackId: UA-42523801-3
