menu:
  Home: /
  Archives: /archives
  About Me: /aboutme
  RSS: /atom.xml

# duoshuo comment
duoshuo: false
duoshuo_name:

#友言
youyan: true
youyan_id: 1736636

# google analytics
googleTrackId: UA-42523801-1
